// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://plvnwsyjyffrgchevqvh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBsdm53c3lqeWZmcmdjaGV2cXZoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjI1MjMzNzUsImV4cCI6MjA3ODA5OTM3NX0.ch_qR2Keqwrk7InygL7MGLI5YgRML_dLRQuLGZKvNl0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});